import { useState, useEffect } from 'react'
import { api } from './api'
import type { AnalysisReport, Signal } from './types'
import { TopBar } from './components/TopBar'
import { Sidebar } from './components/Sidebar'
import { ContradictionEngine } from './components/ContradictionEngine'
import { AlphaScoreCard } from './components/AlphaScoreCard'
import { AgentGrid } from './components/AgentGrid'
import { QuantPanel } from './components/QuantPanel'
import { BlueprintOverlay, type TourStep } from './components/BlueprintOverlay'
import { ZenithDashboard } from './components/ZenithDashboard'

type View = 'zenith' | 'contradiction' | 'analysis'

// ── Tour step definitions ─────────────────────────────────────────────────

const CONTRADICTION_TOUR: TourStep[] = [
  {
    label: 'STEP 01', side: 'right',
    title: 'The Source of Truth',
    body:  'Paste or upload SEC/SEBI filing text. Our engine vectorizes 500+ pages in seconds using pgvector embeddings.',
    anchor: '#panel-filing',
  },
  {
    label: 'STEP 02', side: 'left',
    title: 'The Pulse',
    body:  'Live news headlines with sentiment scores. We track the "Hype Gap" between retail narrative and insider moves.',
    anchor: '#panel-news',
  },
  {
    label: 'STEP 03', side: 'left',
    title: 'The Alpha Verdict',
    body:  'AI truth-checking engine. We flag when a CEO\'s filing contradicts what analysts are reporting in the market.',
    anchor: '#panel-verdict',
  },
]

const ZENITH_TOUR: TourStep[] = [
  {
    label: 'STEP 01', side: 'right',
    title: 'Zenith Score',
    body:  'Composite 0–100 score weighted across 3 fast agents: Quant (40%), Sentiment (30%), Insider (30%). Higher = stronger buy signal.',
    anchor: '#tour-zenith-score',
  },
  {
    label: 'STEP 02', side: 'left',
    title: 'Narrative Conflict',
    body:  'Detects when management filings contradict recent news. CRITICAL level means the CEO\'s story doesn\'t match the market\'s.',
    anchor: '#tour-narrative-conflict',
  },
  {
    label: 'STEP 03', side: 'right',
    title: 'Sentiment Divergence',
    body:  'Compares retail social sentiment vs insider trading activity. A large gap signals potential manipulation risk.',
    anchor: '#tour-sentiment',
  },
  {
    label: 'STEP 04', side: 'left',
    title: 'Quant Insight',
    body:  'Technical pattern detection (Head & Shoulders, Breakout) with historical backtest win rates. Confidence = pattern quality.',
    anchor: '#tour-quant-insight',
  },
]

const ALPHA_TOUR: TourStep[] = [
  {
    label: 'STEP 01', side: 'right',
    title: 'Alpha Score',
    body:  'Weighted composite score from all 5 agents. Filing (25%), News (20%), Insider (20%), Quant (20%), Sentiment (15%).',
    anchor: '#tour-alpha-score',
  },
  {
    label: 'STEP 02', side: 'left',
    title: 'Agent Breakdown',
    body:  'Per-agent scores shown as bars. Green = bullish signal, amber = neutral, red = bearish. Failed agents default to 50.',
    anchor: '#tour-agent-breakdown',
  },
  {
    label: 'STEP 03', side: 'left',
    title: 'Key Risks',
    body:  'Top 3 risks extracted from real agent data — news headlines, insider activity, technical patterns, and filing passages.',
    anchor: '#tour-key-risks',
  },
  {
    label: 'STEP 04', side: 'bottom',
    title: 'AI Summary',
    body:  'Plain-English investment briefing synthesised from all agent outputs. Generated by Gemini or rule-based fallback.',
    anchor: '#tour-ai-summary',
  },
]

interface HistoryItem {
  ticker: string
  signal: Signal
  score: number
  time: string
}

export default function App() {
  const [report, setReport]     = useState<AnalysisReport | null>(null)
  const [loading, setLoading]   = useState(false)
  const [error, setError]       = useState<string | null>(null)
  const [view, setView]         = useState<View>('zenith')
  const [history, setHistory]   = useState<HistoryItem[]>([])
  const [showTour, setShowTour] = useState(false)

  // Tour steps depend on which view is active
  const tourSteps = view === 'zenith'       ? ZENITH_TOUR
                  : view === 'analysis'     ? ALPHA_TOUR
                  : CONTRADICTION_TOUR

  const tourFinishLabel = view === 'zenith'   ? 'START ANALYSING'
                        : view === 'analysis' ? 'VIEW RESULTS'
                        : 'ENTER TERMINAL'

  // Show tour on first visit to each page
  useEffect(() => {
    const key = `iq_tour_${view}`
    const seen = localStorage.getItem(key)
    if (!seen) {
      setTimeout(() => setShowTour(true), 500)
    }
  }, [view])

  const dismissTour = () => {
    setShowTour(false)
    localStorage.setItem(`iq_tour_${view}`, '1')
  }

  const handleAnalyse = async (ticker: string) => {
    setLoading(true)
    setError(null)
    setView('analysis')
    try {
      const r = await api.analyse(ticker)
      setReport(r)
      setHistory(prev => [
        {
          ticker: r.ticker,
          signal: r.signal,
          score: r.alpha_score,
          time: new Date().toLocaleTimeString(),
        },
        ...prev.slice(0, 19),
      ])
    } catch (e: unknown) {
      setError(e instanceof Error ? e.message : 'Analysis failed')
    } finally {
      setLoading(false)
    }
  }

  return (
    <div className="flex flex-col h-screen overflow-hidden" style={{ background: '#0B0E11' }}>
      {showTour && (
        <BlueprintOverlay
          steps={tourSteps}
          onDismiss={dismissTour}
          finishLabel={tourFinishLabel}
        />
      )}

      <TopBar
        onAnalyse={handleAnalyse}
        loading={loading}
        onShowTour={() => { localStorage.removeItem(`iq_tour_${view}`); setShowTour(true) }}
      />

      <div className="flex flex-1 min-h-0">
        <Sidebar
          activeView={view}
          onView={setView}
          history={history}
          onHistoryClick={handleAnalyse}
        />

        {/* Main workspace */}
        <main className="flex-1 flex flex-col min-w-0 overflow-hidden">

          {/* Workspace header */}
          <div className="px-5 py-2.5 flex items-center justify-between"
            style={{ borderBottom: '1px solid #2B2F36', background: '#131720', flexShrink: 0 }}>
            <div>
              {report ? (
                <h1 className="text-base font-bold"
                  style={{ fontFamily: 'Playfair Display, serif', color: '#E8EAF0' }}>
                  AUDIT: {report.ticker} [{report.company_name}]
                </h1>
              ) : (
                <h1 className="text-base font-bold"
                  style={{ fontFamily: 'Playfair Display, serif', color: '#5A6070' }}>
                  {view === 'contradiction' ? 'CONTRADICTION ENGINE' : 'ALPHA ANALYSIS'}
                </h1>
              )}
            </div>
            <div className="flex items-center gap-2 text-[9px]"
              style={{ color: '#5A6070', fontFamily: 'JetBrains Mono, monospace' }}>
              <span>{new Date().toLocaleString()}</span>
              <span style={{ color: '#2B2F36' }}>|</span>
              <span>NOT FINANCIAL ADVICE</span>
            </div>
          </div>

          {/* Error banner */}
          {error && (
            <div className="mx-5 mt-3 px-3 py-2 flex items-center gap-2 text-xs"
              style={{
                border: '1px solid #E31B23', background: '#3D0A0C',
                color: '#E31B23', fontFamily: 'JetBrains Mono, monospace', flexShrink: 0,
              }}>
              <span>✗ ERROR:</span>
              <span className="flex-1">{error}</span>
              <button onClick={() => setError(null)}
                style={{ color: '#E31B23', background: 'none', border: 'none', cursor: 'pointer' }}>
                ✕
              </button>
            </div>
          )}

          {/* Loading */}
          {loading && (
            <div className="flex-1 flex flex-col items-center justify-center gap-4">
              <div className="text-4xl animate-pulse"
                style={{ fontFamily: 'Playfair Display, serif', color: '#E31B23' }}>
                ◈
              </div>
              <div className="text-xs tracking-widest uppercase"
                style={{ color: '#5A6070', fontFamily: 'JetBrains Mono, monospace' }}>
                Running 5-agent analysis pipeline
              </div>
              <div className="flex gap-4 text-[10px]"
                style={{ color: '#3A3F4A', fontFamily: 'JetBrains Mono, monospace' }}>
                {['Filing', 'News', 'Sentiment', 'Insider', 'Quant'].map(a => (
                  <span key={a} className="animate-pulse">{a}</span>
                ))}
              </div>
            </div>
          )}

          {/* Content */}
          {!loading && (
            <div className="flex-1 overflow-y-auto p-5 space-y-4">

              {view === 'zenith' && (
                <ZenithDashboard />
              )}

              {view === 'contradiction' && (
                <div className="h-full" style={{ border: '1px solid #2B2F36', background: '#131720' }}>
                  <ContradictionEngine ticker={report?.ticker} />
                </div>
              )}

              {view === 'analysis' && (
                <>
                  {!report && (
                    <div className="flex flex-col items-center justify-center py-20 gap-6">
                      <div className="text-5xl font-bold"
                        style={{ fontFamily: 'Playfair Display, serif', color: '#2B2F36' }}>
                        ZENITH IQ
                      </div>
                      <div className="text-xs tracking-widest"
                        style={{ color: '#3A3F4A', fontFamily: 'JetBrains Mono, monospace' }}>
                        ENTER A TICKER ABOVE TO BEGIN AUDIT
                      </div>
                      <div className="grid grid-cols-5 gap-0 mt-4"
                        style={{ border: '1px solid #2B2F36' }}>
                        {['📄 Filing', '📰 News', '💬 Sentiment', '👤 Insider', '📈 Quant'].map((a, i, arr) => (
                          <div key={a} className="px-6 py-4 text-center text-[10px]"
                            style={{
                              borderRight: i < arr.length - 1 ? '1px solid #2B2F36' : 'none',
                              color: '#3A3F4A', fontFamily: 'JetBrains Mono, monospace',
                            }}>
                            {a}
                          </div>
                        ))}
                      </div>
                    </div>
                  )}

                  {report && (
                    <div className="space-y-4">
                      <AlphaScoreCard report={report} />
                      <div style={{ border: '1px solid #2B2F36', background: '#131720' }}>
                        <AgentGrid results={report.agent_results} />
                      </div>
                      {report.agent_results['QuantAgent'] && (
                        <QuantPanel result={report.agent_results['QuantAgent']} />
                      )}
                    </div>
                  )}
                </>
              )}
            </div>
          )}
        </main>
      </div>
    </div>
  )
}
